sugarlabs/musicblocks-v4-lib

src/.prototype/syntaxElements/@types/primitiveElements.d.ts
src/.prototype/syntaxElements/@types/primitiveTypes.d.ts
src/.prototype/syntaxElements/primitiveElements.ts

- Reorganize code in `primitiveElements.ts`
- Document code in `primitiveTypes.d.ts`, `primitiveElements.d.ts`, and `primitiveElements.ts`

Reorganize and document files related to primitives

---

src/.prototype/syntaxElements/primitiveElements.test.ts
src/.prototype/syntaxElements/primitiveElements.ts
src/.prototype/syntaxElements/programElements/operationElements.test.ts
src/.prototype/syntaxElements/programElements/operationElements.ts

- Add `&&` and `||` operators in `primitiveElements.ts`
- Add unit-tests for said operators
- Reorganize class hierarchy in `operationElements.ts` by creating a `BinaryOperationElement` abstract super class
- Add Boolean _AND_ and _OR_ operations in `operationElements.ts`
- Add unit-tests for said operations

Reorganize files related to Operations

---

src/.prototype/syntaxElements/sample.ts

Add a sample file that integrates `syntaxElements` to create a program that finds the n-th fibonacci number using the created prototype constructs to demonstrate the new instruction definition and execution framework.

Add sample fibonacci program

---

src/.prototype/syntaxElements/primitiveElements.test.ts
src/.prototype/syntaxElements/primitiveElements.ts

Binary operations and tests in Numbers: TInt and TFloat

---

src/.prototype/musicutils/ts/@types/temperament.d.ts
src/.prototype/musicutils/ts/temperament.test.ts
src/.prototype/musicutils/ts/temperament.ts

@meganindya I have tried to incoporate the comments on my previous PR and elsewhere into this one. Could you please have a look? I have ported a smaller file `temperament.py` entirely with its testcases and some parts of `musicutils.py` which were being utilised by this file. All the test cases seem to pass.

Temperament - port to TypeScript

---

src/.prototype/musicutils/ts/@types/errors.d.ts
src/.prototype/musicutils/ts/errors.ts
src/.prototype/musicutils/ts/keySignature.ts
src/.prototype/musicutils/ts/temperament.ts

try-catch error handling in typescript export of musicutils

---

src/.prototype/musicutils/ts/@types/currentPitch.d.ts
src/.prototype/musicutils/ts/currentPitch.test.ts
src/.prototype/musicutils/ts/currentPitch.ts
src/.prototype/musicutils/ts/temperament.ts

This file uses several other files directly or indirectly. Currently this file itself is ported to typescript, will update test cases when dependencies are done. Thanks

Porting currentPitch.py to typescript

---

src/.prototype/musicutils/ts/@types/currentPitch.d.ts
src/.prototype/musicutils/ts/README.md
src/.prototype/musicutils/ts/currentPitch.ts

- Created `README.md` in `src/.prototype/musicutils/ts/`
- Add documentation for the `CurrentPitch` class in `src/.prototype/musicutils/ts/currentPitch.ts`

Add documentation for currentPitch.ts

---

.markdownlint.jsonc
src/.prototype/musicutils/ts/README.md

Reference #30 
Updates the Temperament section of `musicutils/README.md`

Add documentation for temperament.ts

---

src/.prototype/musicutils/ts/@types/scale.d.ts
src/.prototype/musicutils/ts/README.md
src/.prototype/musicutils/ts/scale.ts

Reference #30
Updates the Scale section of musicutils/README.md

Add documentation for scale.ts

---

src/.prototype/musicutils/ts/README.md
src/.prototype/musicutils/ts/musicUtils.ts

##Description:
Issue Reference: #30 
This patch does the following:
- Adds the Music Utils section in musicutils/ts/README.md
- Updates some documentation in musicUtils.ts
Please review this and share your feedback @meganindya.
Thanks.

Add documentation for musicUtils.ts

---

src/.prototype/musicutils/ts/@types/keySignature.d.ts
src/.prototype/musicutils/ts/currentPitch.ts
src/.prototype/musicutils/ts/keySignature.test.ts
src/.prototype/musicutils/ts/keySignature.ts

Remove error status from keySignature.ts

---

src/.prototype/musicutils/ts/scale.test.ts

Issue Reference: #25
This PR adds test cases for scale.ts. The code coverage is 100%. All the functions are covered.
Please review this. @meganindya 
Thanks

Added Test cases to scale.test.ts

---

src/.prototype/musicutils/ts/@types/keySignature.d.ts
src/.prototype/musicutils/ts/README.md
src/.prototype/musicutils/ts/keySignature.ts

Add documentation for keySignature.ts

---

src/.prototype/musicutils/ts/keySignature.test.ts
src/.prototype/musicutils/ts/keySignature.ts

Add more tests to keySignature.test.ts

---

src/.prototype/syntax-core/primitiveElements.test.ts
src/.prototype/syntax-core/primitiveElements.ts

issue reference:- #6 
I have added operations, please review @meganindya

Operations and tests on string

---

.eslintrc.json
src/@types/syntax/data.d.ts
src/@types/syntax/elementsCore.d.ts
src/@types/syntax/symbolTable.d.ts
src/syntax/elements/core/elementArgument.ts
src/syntax/elements/core/elementInstruction.ts
src/syntax/elements/core/elementSyntax.spec.ts
src/syntax/elements/core/elementSyntax.ts
src/syntax/symbol-table/symbolTable.spec.ts
src/syntax/symbol-table/symbolTable.ts

- maintains 3 tables: **global**, **program**, **routine**
- **global** variables are shared across all programs and routines
- **program** variables are global within a program and private elsewhere
- **routine** variables are global within a routine and private elsewhere
- can **add**, **fetch**, **remove** variables with all specificity
- can **flush** tables with all specificity
closes #77.

Syntax: Build the Symbol Table

---

src/@types/syntax/elementSpecification.d.ts
src/@types/syntax/elementsCore.d.ts
src/syntax/elements/core/elementArgument.ts
src/syntax/elements/core/elementInstruction.ts
src/syntax/elements/core/elementSyntax.spec.ts
src/syntax/elements/core/elementSyntax.ts
src/syntax/elements/program/boxes/elementBox.spec.ts
src/syntax/elements/program/boxes/elementBox.ts
src/syntax/elements/program/boxes/elementBoxIdentifier.spec.ts
src/syntax/elements/program/boxes/elementBoxIdentifier.ts
src/syntax/elements/program/operators/elementOperatorMath.spec.ts
src/syntax/elements/program/operators/elementOperatorMath.ts
src/syntax/elements/program/values/elementValue.spec.ts
src/syntax/elements/program/values/elementValue.ts
src/syntax/elements/specification.spec.ts
src/syntax/elements/specification.ts

- Draft the schema
- Build the specification table
- Add unit tests to check instantiation and other entry properties
closes #73.

Syntax: Build the Syntax Element Schema

---

src/@types/execution.d.ts
src/execution/interpreter.ts
src/execution/symbolTable.ts
src/syntax/elements/boxes/elementBox.ts
src/syntax/elements/boxes/elementBoxIdentifier.ts

- `declareVariable`
- `queryVariable`
- Use above functions in `ElementBox.ts` and `ElementBoxIdentifier.ts`
closes #89.

Interpreter: Add proxy functions for basic symbol table operations

---

src/@types/execution.d.ts
src/@types/syntaxTree.d.ts
src/execution/parser.spec.ts
src/execution/parser.ts
src/syntax/tree/node.ts
src/syntax/tree/syntaxTree.ts

- validate argument sequence
- generate argument sequence
- set execution root item
- adds function to fetch next execution element in sequence
- stack trace
closes #76.

Parser: Create Parser

---

src/@types/execution.d.ts
src/execution/interpreter.ts
src/execution/parser.ts

- `overrideProgramCounter`
- `releaseProgramCounter`
closes #90.

Interpreter: Add proxy functions for parser

---

src/@types/execution.d.ts
src/@types/specification.d.ts
src/execution/parser.spec.ts
src/execution/parser.ts
src/library/elements/elementConditional.ts
src/library/elements/elementLoop.ts

- `ElementIf`
- `ElementRepeat`
closes #82.

Add some concrete element

---

src/@types/specification.d.ts
src/execution/interpreter.spec.ts
src/execution/interpreter.ts
src/library/elements/elementPrint.ts
src/library/specification.ts
src/syntax/warehouse/warehouse.spec.ts

Interpreter: Add basic non-preemptive execution logic

---

Dockerfile

https://github.com/sugarlabs/musicblocks-v4-lib/issues/87  doesn't have "needs help", but I've fixed it.

Dockerfile: change to the alpine image

---

.github/workflows/CI.yml
.github/workflows/linter.yml

- Remove unnecessary comments
- Split CI workflow into two parallel jobs: Smoke Test and Regression Test

Update workflow files

---

src/@types/execution.d.ts
src/@types/syntaxTree.d.ts
src/execution/interpreter.ts
src/execution/parser.ts
src/index.ts
src/syntax/elements/elementArgument.ts
src/syntax/elements/elementInstruction.ts
src/syntax/elements/elementSyntax.ts
src/syntax/specification/specification.ts
src/syntax/tree/syntaxTree.ts

- Update docs
- Update type signatures
- Expose functions, classes, types that is required to interact with the execution engine
closes #110.

Expose API for use in musicblocks-v4

---

package.json
yarn.lock

GitHub issue: #108
* updated package to the latest
* updated yarn.lock accordingly

chore: [#108] Update package dependencies

---

CHANGELOG.md
package.json

- Add `CHANGELOG.md`
- Bump package version to `1.0.1`

Prepare Release v1.0.1

---

src/@types/specification.d.ts
src/index.ts
src/library/specification.ts
src/syntax/specification/specification.spec.ts
src/syntax/specification/specification.ts
src/syntax/tree/syntaxTree.spec.ts
src/syntax/warehouse/warehouse.spec.ts
src/syntax/warehouse/warehouse.ts

- remove 1-level `category` field
- add a 2-level `classification` map field of `group` and `category`

refactor(specification): replace category with classification

---

src/@types/elements.d.ts
src/@types/specification.d.ts
src/execution/interpreter/index.spec.ts
src/execution/interpreter/index.ts
src/execution/scope/index.spec.ts
src/execution/scope/index.ts
src/index.ts
src/library/elements/elementBox.spec.ts
src/library/elements/elementBox.ts
src/library/elements/elementBoxIdentifier.spec.ts
src/library/elements/elementBoxIdentifier.ts
src/library/elements/elementConditional.ts
src/library/elements/elementLoop.ts
src/library/elements/elementOperatorMath.spec.ts
src/library/elements/elementOperatorMath.ts
src/library/elements/elementPrint.ts
src/library/elements/elementProgram.ts
src/library/elements/elementValue.spec.ts
src/library/elements/elementValue.ts
src/library/index.ts
src/syntax/elements/elementArgument.spec.ts
src/syntax/elements/elementArgument.ts
src/syntax/elements/elementInstruction.ts
src/syntax/specification/index.spec.ts
src/syntax/specification/index.ts

Refactor syntax add scope
