src/.prototype/syntaxElements/@types/structureElements.d.ts
src/.prototype/syntaxElements/structureElements.test.ts
src/.prototype/syntaxElements/structureElements.ts

- Reorganize code in `structureElements.ts`
- Fix variable naming inconsistencies in `structureElements.d.ts` and `structureElements.ts`
- Document `structureElements.d.ts` and `structureElements.ts`

Reorganize and document files related to structural elements

---

src/.prototype/syntaxElements/@types/structureElements.d.ts
src/.prototype/syntaxElements/programElements/conditionalElements.test.ts
src/.prototype/syntaxElements/programElements/conditionalElements.ts
src/.prototype/syntaxElements/programElements/dataElements.test.ts
src/.prototype/syntaxElements/programElements/dataElements.ts
src/.prototype/syntaxElements/programElements/loopElements.test.ts
src/.prototype/syntaxElements/programElements/loopElements.ts
src/.prototype/syntaxElements/programElements/operationElements.test.ts
src/.prototype/syntaxElements/programElements/operationElements.ts
src/.prototype/syntaxElements/programElements/valueElements.test.ts
src/.prototype/syntaxElements/programElements/valueElements.ts
src/.prototype/syntaxElements/structureElements.test.ts
src/.prototype/syntaxElements/structureElements.ts

- Standardize argument setters/getters to start with `arg`
- Rename `BoxElement` to `DataElement`
- Add `update` method to `ValueElement` classes
- Add unit-tests for the said
- Add `IfElseElement` and `IfThenElement` under `ConditionalElement` namespace
- Add unit-tests for the said
- Add `RepeatLoopElement` under `LoopElement` namespace
- Add unit-tests for the said

Patch existing programElements and add new elements

---

src/.prototype/syntaxElements/programElements/conditionalElements.ts
src/.prototype/syntaxElements/programElements/dataElements.test.ts
src/.prototype/syntaxElements/programElements/dataElements.ts
src/.prototype/syntaxElements/programElements/loopElements.test.ts
src/.prototype/syntaxElements/programElements/loopElements.ts
src/.prototype/syntaxElements/programElements/miscellaneousElements.ts
src/.prototype/syntaxElements/programElements/valueElements.ts
src/.prototype/syntaxElements/structureElements.test.ts
src/.prototype/syntaxElements/structureElements.ts

`structureElements.ts`:
- Remove private `TPrimitive` object for `ArgumentDataElement`
- Add Dummy Instruction Element `DummyElement`
`structureElements.test.ts`
- Update tests
`conditionalElements.ts`
- Add `argCondition` getter and setter for argument label `condition`
`loopElements.ts`
- Fix internal logic of `RepeatLoopElement`
`loopElements.test.ts`
- Update tests
`miscellaneousElements.ts`
- Add dummy `PrintElement` for demonstration
`valueElements.ts`
- Store private `TPrimitive` object in `ValueElement` which was removed from `ArgumentDataElement`
- Add `DataValueElement`
`dataElements.ts`
- Add getters for `ValueElement` and `TPrimitive` data references in generated `DataValueElement`
`dataElements.test.ts`
- Update tests

Syntax elements patch and feature addition

---

src/.prototype/broker/@types/syntaxHandler.d.ts
src/.prototype/broker/syntaxHandler.test.ts
src/.prototype/broker/syntaxHandler.ts
src/.prototype/syntax-core/@types/AST.d.ts
src/.prototype/syntax-core/@types/context.d.ts
src/.prototype/syntax-core/@types/structureElements.d.ts
src/.prototype/syntax-core/@types/symbolTable.d.ts
src/.prototype/syntax-core/AST.ts
src/.prototype/syntax-core/program-elements/conditionalElements.test.ts
src/.prototype/syntax-core/program-elements/conditionalElements.ts
src/.prototype/syntax-core/program-elements/dataElements.test.ts
src/.prototype/syntax-core/program-elements/dataElements.ts
src/.prototype/syntax-core/program-elements/loopElements.test.ts
src/.prototype/syntax-core/program-elements/loopElements.ts
src/.prototype/syntax-core/program-elements/miscellaneousElements.ts
src/.prototype/syntax-core/program-elements/operationElements.test.ts
src/.prototype/syntax-core/program-elements/operationElements.ts
src/.prototype/syntax-core/program-elements/valueElements.test.ts
src/.prototype/syntax-core/program-elements/valueElements.ts
src/.prototype/syntax-core/structureElements.test.ts
src/.prototype/syntax-core/structureElements.ts
src/.prototype/syntax-core/symbolTable.ts
src/.prototype/syntax-core/syntaxElementFactory.test.ts
src/.prototype/syntax-core/syntaxElementFactory.ts

- Add/Remove 'start' elements to AST
- Replace argument `data` getter with `getData` method
- Improve type implementation in syntax element factory
- Pass argument primitives and context to `onVisit`, `onExit`, and `getData`
- Create symbol table and attach functionality to data elements
- Pass symbol table to `onVisit`, `onExit`, and `getData`

Ambient properties for syntax element execution

---

src/.prototype/musicutils/ts/@types/scale.d.ts
src/.prototype/musicutils/ts/scale.test.ts
src/.prototype/musicutils/ts/scale.ts

Addresses #18.
- Add interface `IScale` for class `Scale` in `scale.d.ts`
- Port class `Scale` and all its members in `scale.py` to `scale.ts`
- Add important unit tests re members of the `Scale` class in `scale.test.ts`
**Test verification:**
**Todo:**
- Exhaustively implement remaining test cases for the `Scale` class.

Port scale.py to TypeScript

---

src/.prototype/musicutils/ts/musicutils.test.ts
src/.prototype/musicutils/ts/musicutils.ts

Addresses #18.
Modified from #27. Reworked on the commits by cherry picking and interactive rebasing.
- Port contents of `musicutils.py` to `musicutils.ts`
- Add unit tests in `musicutils.test.ts` re utility functions in `musicutils.ts`
**Test verification:**
**Todo:**
- Add missing error test cases

Port musicutils.py to TypeScript

---

src/.prototype/musicutils/ts/musicutils.test.ts
src/.prototype/musicutils/ts/musicutils.ts

Issue Reference: #25 
This PR adds the remaining testcases for musicutils.ts. Also, one minor change is done in the file `musicutils.ts` as the character `𝄪` takes up 2 spaces and thus a testcase concerning the `stripAccidental` would fail previously.
The code from lines 484 through 486 in the `musicutils.ts` file is unreachable and thus, the testcase concerning jsut that conditional is not possible.
```
if (EQUIVALENT_FLATS.hasOwnProperty(pitchName)) {
return LETTER_NAME;
}
```
Please review this @meganindya.
Thanks.

Add testcases to musicutils.test.ts

---

src/.prototype/musicutils/ts/temperament.ts

Overrides toString method to return the list of frequencies in the instance.

Add missing toString method for temperament.ts

---

src/.prototype/musicutils/ts/musicUtils.test.ts

Issue Reference: #25 
This PR adds the remaining testcases covering the error cases of `findSharpIndex` and `findFlatIndex` methods.
Please review this @meganindya.
Thanks.

Add error testcases to musicutils.test.ts

---

src/.prototype/musicutils/ts/README.md
src/.prototype/musicutils/ts/currentPitch.ts

Addresses #30.
- Add `toString` override method for `CurrentPitch` class in `src/.prototype/musicutils/ts/currentPitch.ts`
- Add `documentation` for `Example` section in `src/.prototype/musicutils/ts/README.md`

Add example docs

---

src/.prototype/musicutils/ts/README.md

Add `readonly` prefix for instance variables of classes `CurrentPitch`, `Temperament`, and `Scale`, which are getters only.

Prefix readonly for getter only instance variables

---

src/.prototype/musicutils/ts/temperament.test.ts
src/.prototype/musicutils/ts/temperament.ts

Issue Reference: #25
This PR adds test cases for temperament.ts. The code coverage is above 80% in temperament.
Also, there is a minor change in the if-else statement of temperament.ts. `!(noteName in this._genericNoteNames)` at line 431 in was always returning true to I have to change it into `!this._genericNoteNames.includes(noteName)`. 
All test cases are passed.
Please review the code @meganindya .
Thanks.

Added test cases to Temperament.test.ts

---

src/.prototype/musicutils/ts/keySignature.ts

The distance of (a, b) was calculated as (a - b) but should be
calculated as (b - a). This has been fixed in both the scalar and
semitone distance methods. Since these methods are used in the invert
method, the order of arguments has been adjusted there as well.
The scalar distance calculation was both overly complex and wrong. An
approach similar to the one used to calculate semitone distance is
used instead.

semitone and scalar distance calculation

---

src/musicUtils/currentPitch.ts
src/musicUtils/keySignature.ts

Removed `_assignSolfegeNoteNames`, `_assignEastIndianSolfegeNoteNames`, `_assignScalarModeNumbers` from `keySignature.ts` and put their effective code directly inside the constructor. The condition where they could throw errors isn't at all reached, so no errors thrown. Consequently, `KeySignature` and in turn `CurrentPitch` don't throw error on instantiation.

KeySignature instantiation won't throw error

---

.eslintrc.json
src/@types/elementsStructure.d.ts
src/syntax/elements/ElementArgument.spec.ts
src/syntax/elements/ElementArgument.ts
src/syntax/elements/ElementInstruction.ts
src/syntax/elements/ElementSyntax.spec.ts
src/syntax/elements/ElementSyntax.ts

closes #70.
- class `ElementSyntax`
- tests for `ElementSyntax`
- class `ElementArgument`
- class `ElementValue`
- tests for `ElementValue`
- class `ElementExpression`
- tests for `ElementExpression`
- class `ElementInstruction`
- class `ElementStatement`
- class `ElementBlock`

Syntax: Build constructs to represent syntax elements

---

src/@types/syntax/elementsCore.d.ts
src/syntax/elements/core/elementArgument.spec.ts
src/syntax/elements/core/elementArgument.ts
src/syntax/elements/core/elementSyntax.spec.ts
src/syntax/elements/core/elementSyntax.ts

Renames `ElementValue` to `ElementData` and all literal references of value element to data element.
closes #80.

Syntax: Rename value element to data element

---

package-lock.json
package.json
src/@types/syntax/elementSpecification.d.ts
src/@types/syntax/elementsCore.d.ts
src/syntax/elements/warehouse.spec.ts
src/syntax/elements/warehouse.ts

- add an element instance
- get an element instance
- remove an element instance
- get count of element instances for an element name
- get count of element instances for all element names
- get count of element instances for an element kind
- get count of element instances for all element kinds
- get count of element instances for an element type
- get count of element instances for all element types
- get count of element instances for an element category
- get count of element instances for all element categories
- reset the warehouse
closes #74.

Syntax: [feat] Create syntax element warehouse with tests

---

src/@types/syntaxTree.d.ts
src/syntax/tree/node.ts
src/syntax/tree/syntaxTree.spec.ts
src/syntax/tree/syntaxTree.ts

- Add `nodeID` field in each output snapshot
- Input snapshots don't require `nodeID` field

Syntax Tree: [snapshot] Pack node ID

---

src/syntax/specification/specification.spec.ts
src/syntax/specification/specification.ts

closes #112.
In first commit-
In second commit-

Specification: Added validation in functions

---

src/@types/elements.d.ts
src/@types/specification.d.ts
src/@types/syntaxTree.d.ts
src/execution/parser.ts
src/library/elements/elementBox.ts
src/library/elements/elementBoxIdentifier.ts
src/library/elements/elementConditional.ts
src/library/elements/elementLoop.ts
src/library/elements/elementOperatorMath.ts
src/library/elements/elementPrint.ts
src/library/elements/elementProgram.ts
src/library/elements/elementValue.ts
src/syntax/elements/elementArgument.ts
src/syntax/elements/elementInstruction.ts
src/syntax/elements/elementSyntax.spec.ts
src/syntax/elements/elementSyntax.ts
src/syntax/specification/specification.spec.ts
src/syntax/specification/specification.ts
src/syntax/tree/node.ts
src/syntax/tree/syntaxTree.ts
src/syntax/warehouse/warehouse.ts

replace type from `TElementName`, `TElementNameData`, `TElementNameExpression`, `TElementNameStatement`, `TElementNameBlock` to `string` for element name

Remove custom type reliance for element name

---

src/@types/specification.d.ts
src/index.ts
src/syntax/specification/specification.spec.ts
src/syntax/specification/specification.ts

closes #113. 
**Changes** - 
- added interface `IElementSpecificationSnapshot` in `specification.d.ts`
- added `generateSnapshot` function in `specification.ts`
Please review once whether the added `generateSnapshot` function meets your expectation, and if not please suggest the required changes
I will add the tests once the `generateSnapshot` function is reviewed and passed by the reviewer.
**Help Needed**-
- `@returns` comment for the function is exceeding 100 chars so I added a new line character in between, how to solve that without adding a new line.
- Should I change function name with `elementsSpecGenerateSnapshot` otherwise it will concide with [`generateSnapshot()` ](https://github.com/sugarlabs/musicblocks-v4-lib/blob/c4e49fcda7b5038dce83d62d3f354c0391398951/src/syntax/tree/synta …

Specification: Add snapshot function

---

src/@types/specification.d.ts
src/@types/syntaxTree.d.ts
src/execution/interpreter.spec.ts
src/index.ts
src/library/specification.ts
src/syntax/specification/specification.spec.ts
src/syntax/specification/specification.ts
src/syntax/tree/syntaxTree.spec.ts
src/syntax/tree/syntaxTree.ts

- Adds provision to provide initialisation value in the snapshots of data elements. Provided value is updated in the syntax tree node's element instance after syntax tree node is added.
- Adds provision to provide accepted values constraint in specification.
- Adds value assignment check functions.
- Performs checks before assigning values from snapshot.
- Adds a function to directly assign value to syntax tree node's data element instance.

Syntax tree: Provide initialisation values in snapshot of data elements

---

CHANGELOG.md
package.json

- bump down `v1.0.0` to `v0.1.0` prerelease
- bump down `v1.0.1` to `v0.2.0` prerelease

Chore: fix semantic versioning violations

---

.gitignore

Path for `yarn test --coverage` is `/src/coverage` not `/coverage`

Fix: Testing Coverage Path in .gitignore
